//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactWithSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMaster
    {
        public long AccountMasterID { get; set; }
        public string AccountMaster1 { get; set; }
        public Nullable<long> PaidTo { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> IsPositvie { get; set; }
    }
}
